= Notes on CJ
:prevent-blank-line:
include::../partials/_header.adoc[]

This document is not formally part of the {cj} specification.

== CJ as Compact Schema
Here is a compact view on which properties are interpreted by {cj}.
It is designed to let humans quickly understand which parts of JSON are 'claimed' by {cj}.

See link:extensible-json.adoc#extension_properties[_Extension Properties_].

.Spec including aliases, multilingual labels and Knowledge Graph extension. [To be added: Styling]
----
("graph" | "graphs") ARRAY? | GRAPH = OBJECT
    "baseUri" = STRING
    "edgeDefault" = PRIMITIVE
    "id" = STRING | NUMBER
    "label" = STRING | OBJECT
        "language" = STRING // Multilingual Labels
        "value" = STRING // Multilingual Labels
    "(edges" | "edge" | "hyperedges") ARRAY? = OBJECT
        "id" = STRING
        "label" = STRING | OBJECT
            "language" = STRING // Multilingual Labels
            "value" = STRING // Multilingual Labels
        "directed" = BOOLEAN
        "type" = STRING
        "typeNode" = STRING | NUMBER
        "typeUri" = STRING
        "source" | "sources" | "from" = STRING | NUMBER
        "target" | "targets" | "to" = STRING | NUMBER
        ("endpoints" | "endpoint") ARRAY? = OBJECT
            "direction" | "dir" = { "in" | "out" | "undir" }
            "node" = STRING | NUMBER // referenced node id
            "port" = STRING | NUMBER // referenced port id
            "type" = STRING
            "typeNode" = STRING | NUMBER
            "typeUri" = STRING
        "graph" --> GRAPH
    ("nodes"|"node") ARRAY? = OBJECT
        "id" = STRING | NUMBER
        "label" = STRING | OBJECT
            "language" = STRING // Multilingual Labels
            "value" = STRING // Multilingual Labels
        "content" = STRING | OBJECT // Knowledge graph extension
        "contentType" = STRING // Knowledge graph extension
        "graph" --> GRAPH
        "ports" ARRAY? --> PORT
PORT = OBJECT
    "id" = STRING | NUMBER
    "label" = STRING | OBJECT
        "language" = STRING // Multilingual Labels
        "value" = STRING // Multilingual Labels
    "ports" ARRAY --> PORT
----

How to read:
[cols="3d,8d"]
|===
| Line | `("graph" \| "graphs") ARRAY? \| GRAPH = OBJECT`
2+| Line -> Key `=` Value
| Key | `("graph" \| "graphs") ARRAY? \| GRAPH`
| Value | OBJECT
2+| Key -> JSON Paths joined with OR (`\|`)
| JSON Path 1 | `("graph" \| "graphs") ARRAY?`
| JSON Path 2 | `GRAPH` (special case of a type name)
2+| JSON Path -> Steps separated by space
| JSON Path 1, Step 1 | `("graph" \| "graphs")`
| JSON Path 1, Step 2 | `ARRAY?`
2+| Step processed like a regular expression
| JSON Path 1, Step 1 | Property `graph` or property `graphs`
| JSON Path 1, Step 2 | optional step into an array
| JSON Path 2 | type _GRAPH_
|===

How to read, attempt 2:

[cols="2m,4d"]
|===
|("graph" \| "graphs") | in an object property `graph` or `graphs`,
| ARRAY? | maybe going into an array
| \| GRAPH | or coming altogether from the type variable _GRAPH_
| = | querying for a JSON value
| OBJECT | matching on type JSON object. This line defines all matching objects are claimed by CJ. However, properties within these objects are split again in CJ and JSON.
|===



== Background

=== Overview
.How to read this
- Each line implies a match for our format, i.e. the listed properties are considered to be part of our format and not JSON data.
- Each line is a path of white-space separated steps.
- STRING, BOOLEAN, NUMBER, NULL are JSON primitive types.
- OBJECT and ARRAY are the JSON container types.
- Other uppercase names are _custom types_.
- Syntax from JSON:
** Strings in `"` (double quotes) denotes JSON property names.
- We re-use syntax from regular expressions, namely
** OR `|` (pipe symbol) for alternatives
** OPTIONAL `?` (question mark) for optional elements
** GROUPS `(` and `)` (braces) for grouping elements
- Our syntax
** The `-->` (arrow) references a previously defined type
** The `=` (equals sign) defines expected type
** Nesting implies the parent paths are used like a prefix, recursively

=== JSON as a Key-Value Map: JsonPath -> JSON primitive value
JSON has only two container types: objects and arrays.
Objects are key-value maps, where keys are strings and values can be any JSON type.
Arrays are ordered lists of JSON values, where keys are integer indexes.
Any nesting of JSON container types can be represented as a path from root to leaf.
Let us re-use syntax from JSON an put strings and double quotes and integers as numbers without quotes. Path separator is a slash (`/`). This is also known as JsonPath.
A ke-value map uses the syntax _key_ = _value_

.Example JSON
----
{
  "graph": {
    "nodes": [
      {
        "id": 1,
        "label": "Node 1"
      },
      {
        "id": 2,
        "label": "Node 2"
      }
    ],
    "edges": [
      {
        "source": 1,
        "target": 2,
        "label": "Edge 1"
      }
    ]
  }
}
----

.Example as Key-Value Map
----
/"graph"/"nodes"/0/"id" = 1
/"graph"/"nodes"/0/"label" = "Node 1"
/"graph"/"nodes"/1/"id" = 2
/"graph"/"nodes"/1/"label" = "Node 2"
/"graph"/"edges"/0/"source" = 1
/"graph"/"edges"/0/"target" = 2
/"graph"/"edges"/0/"label" = "Edge 1"
----

=== JsonPath Queries
Next we use the JsonPath expressions as queries. For that purpose, we extend the syntax with unquoted, upper-case strings, denoting type queries:
OBJECT, ARRAY, NUMBER, STRING, BOOLEAN, NULL.
These type queries can only be used to restrict which types a _value_  can have.

.Examples
- `/"graph"/"nodes"/0/"id" =` resolves to a single integer (`1`).
- `/"graph"/"nodes" = ARRAY` resolves to an array with two nodes (1 and 2).
- `/"graph"/"nodes" = BOOLEAN` resolves to an empty set. No element matches the query.
- `/ = OBJECT` resolves to the root object.
- `/"graph"` resolves to the big graph object.
- `/"graph" = OBJECT` resolves to the big graph object.
- `/"graph" = ARRAY` resolves to an empty set.

Next we borrow a trick from Python or YAML: using white-space.
Instead of slashes, we can use newline and indentation.
Additionally, a path is the prefix for any number of directly nested (indented) paths.

.Example
****
Using syntax like
----
"aaa" = 1
    "bbb" = STRING
    "ccc" = 3
        "ddd" = ARRAY
    "eee" = 5
----

we mean
----
"aaa" = 1
"aaa"/"bbb" = STRING
"aaa"/"ccc" = 3
"aaa"/"ccc"/"ddd" = ARRAY
"aaa"/"eee" = 5
----

The syntaxes can also be mixed. So this is also another way to express the same:
----
"aaa" = 1
"aaa"/"bbb" = STRING
"aaa"/"ccc" = 3
    "ddd" = ARRAY
"aaa"/"eee" = 5
----
****


